In [2]:
import pandas as pd
from shutil import copyfile
import os

In [26]:
def create_folder(type_=None, train_data=None, valid_data=None, classes=[], folder='../data'):
    os.mkdir(F'{folder}/{type_}')
    os.mkdir(F'{folder}/{type_}/train')
    os.mkdir(F'{folder}/{type_}/valid')
    os.mkdir(F'{folder}/{type_}/test')

    for label in classes:
        os.mkdir(F'{folder}/{type_}/train/{label}')
        os.mkdir(F'{folder}/{type_}/valid/{label}')
        os.mkdir(F'{folder}/{type_}/test/{label}')
    
    for index, elem in train_data.iterrows():
        file_ = elem['filename']
        label = elem[type_]
        if label in classes:
            source = F'{datafolder}/dataset/{file_}'
            target = F'{datafolder}/{type_}/train/{label}/{file_}'
            copyfile(source, target)

    samples = valid_data[labels][type_].value_counts()
    class_ = {}
    for elem in list(zip(samples,samples.index)):
        if elem[1] in classes:
            valid = round(elem[0]*0.5)
            test = elem[0] - valid
            class_[elem[1]] = {'valid':valid, 'test':test}

    for index, elem in valid_data.iterrows():
        file_ = elem['filename']
        name = elem[type_]
        if name in classes:
            samples = class_[name]
            if samples['valid'] > 0:
                class_[name]['valid'] -= 1
                source = F'{folder}/dataset/{file_}'
                target = F'{folder}/{type_}/valid/{name}/{file_}'
                copyfile(source, target)
            else:
                samples['test'] -= 1
                source = F'{folder}/dataset/{file_}'
                target = F'{folder}/{type_}/test/{name}/{file_}'
                copyfile(source, target)

In [10]:
datafolder = './data'

In [11]:
dataset = pd.read_csv('../data/all_data_info.csv'); dataset.head()

,artist,date,genre,pixelsx,pixelsy,size_bytes,source,style,title,artist_group,in_train,filename
0,Barnett Newman,1955.0,abstract,15530.0,6911.0,9201912.0,wikiart,Color Field Painting,Uriel,train_only,True,102257.jpg
1,Barnett Newman,1950.0,abstract,14559.0,6866.0,8867532.0,wikiart,Color Field Painting,Vir Heroicus Sublimis,train_only,True,75232.jpg
2,kiri nichol,2013.0,MISSING,9003.0,9004.0,1756681.0,MISSING,Neoplasticism,MISSING,test_only,False,32145.jpg
3,kiri nichol,2013.0,MISSING,9003.0,9004.0,1942046.0,MISSING,Neoplasticism,MISSING,test_only,False,20304.jpg
4,kiri nichol,2013.0,MISSING,9003.0,9004.0,1526212.0,MISSING,Neoplasticism,MISSING,test_only,False,836.jpg

In [12]:
labels = ['filename', 'artist', 'style', 'genre']

In [48]:
artist = ['Henri Matisse', 'Fernand Leger', 'Salvador Dali', 'Pablo Picasso', 'Vincent van Gogh', 'Rembrandt', 'Claude Monet', 'Peter Paul Rubens', 'Pierre-Auguste Renoir', 'Marc Chagall']
styles = ['Impressionism', 'Baroque', 'Surrealism', 'Post-Impressionism', 'Na√Øve Art (Primitivism)', 'Expressionism', 'Cubism', 'Realism', 'Purism', 'Abstract Expressionism', 'Fauvism']
genres = ['portrait','landscape', 'genre painting',
        'sketch and study',
        'religious painting',
        'still life',
        'nude painting (nu)',
        'cityscape',
        'symbolic painting',
        'flower painting',
        'self-portrait',
        'mythological painting',
        'illustration',
        'abstract',
        'design',
        'interior',]

dataset = dataset.query(F'artist in {artist}')

In [14]:
train = dataset[dataset['in_train']]
train = train[labels]
train.head()

      filename        artist          style          genre
112  40672.jpg     Rembrandt        Baroque       portrait
216  49757.jpg  Claude Monet  Impressionism      landscape
588  60634.jpg     Rembrandt        Baroque  self-portrait
613  41682.jpg  Claude Monet  Impressionism      landscape
615  37256.jpg  Claude Monet  Impressionism      landscape

In [15]:
valid = dataset[~dataset['in_train']]
valid = valid[labels]  
valid.head()

      filename                 artist          style             genre
279  85018.jpg  Pierre-Auguste Renoir  Impressionism  sketch and study
325  68576.jpg              Rembrandt        Baroque     self-portrait
451  67638.jpg              Rembrandt        Baroque          portrait
580  35919.jpg           Claude Monet  Impressionism         landscape
719  37447.jpg              Rembrandt        Baroque  sketch and study

In [24]:
create_folder(type_='artist', train_data=train, valid_data=valid, classes=artist, folder='../data')

In [46]:
create_folder(type_='style', train_data=train, valid_data=valid, classes=styles, folder='../data')

In [49]:
create_folder(type_='genre', train_data=train, valid_data=valid, classes=genres, folder='../data')